//
// Created by Administrator on 2019/10/20.
//

#ifndef NATIVEMEMORYLEAKDETECTOR_LEAKEDOBJECT_H
#define NATIVEMEMORYLEAKDETECTOR_LEAKEDOBJECT_H


class Object {

};


#endif //NATIVEMEMORYLEAKDETECTOR_LEAKEDOBJECT_H
